site_name: Documentation MD

theme:
  logo: images/image_logo.svg
  favicon: images/favicon.png
  name: material
  language: pt-BR
  features:
    - palette.toggle
  palette:
    - scheme: default
      primary: custom
      accent: pink
      toggle:
        icon: material/weather-night
        name: Modo escuro
    - scheme: slate
      primary: custom
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Modo claro

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji

nav:
  - Inicio: index.md
  - Teste:
      - CSS Adicional: teste_extra_css.md
      - JS Adicional: teste_extra_js.md
      - Links: teste_links.md
      - Imagens: teste_img.md
      - Sintax: teste_sintax.md
      - Social Cards: teste_social_card.md
